# Generated by Django 5.2 on 2025-06-17 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manuscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название рукописи')),
                ('file', models.FileField(upload_to='manuscripts/', verbose_name='Файл')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('is_ready_for_print', models.BooleanField(default=False, verbose_name='Готова к печати')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
