# Generated by Django 5.2 on 2025-06-18 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0001_initial'),
        ('projects', '0002_project_budget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manuscript',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='manuscript',
            name='is_ready_for_print',
        ),
        migrations.RemoveField(
            model_name='manuscript',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='manuscript',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manuscripts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='file',
            field=models.FileField(upload_to='manuscripts/', verbose_name='Файл рукописи'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manuscripts', to='projects.project'),
        ),
    ]
